import { MarketInfo, MasterTrader, DBotStrategy, MarketSignal } from '../types/deriv';

export const INITIAL_MARKETS: MarketInfo[] = [
  {
    symbol: 'R_10',
    displayName: 'Volatility 10 Index',
    category: 'Volatility Indices',
    description: 'Low smooth volatility of 10% ideal for beginners.',
    currentPrice: 6812.20,
    change24h: 0.28,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: 'R_25',
    displayName: 'Volatility 25 Index',
    category: 'Volatility Indices',
    description: 'Medium-low volatility of 25% with 2-second tick generation.',
    currentPrice: 24100.50,
    change24h: 1.12,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: 'R_50',
    displayName: 'Volatility 50 Index',
    category: 'Volatility Indices',
    description: 'Balanced volatility of 50% with consistent swing momentum.',
    currentPrice: 51200.80,
    change24h: -0.65,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: 'R_75',
    displayName: 'Volatility 75 Index',
    category: 'Volatility Indices',
    description: 'Constant volatility of 75%. Generates 1 tick every 2 seconds.',
    currentPrice: 845230.45,
    change24h: 1.84,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: 'R_100',
    displayName: 'Volatility 100 Index',
    category: 'Volatility Indices',
    description: 'Maximum standard volatility synthetic market with fast swings.',
    currentPrice: 42109.80,
    change24h: 3.45,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: '1HZ10V',
    displayName: 'Volatility 10 (1s) Index',
    category: 'Volatility Indices',
    description: 'High-frequency 10% volatility index with 1 tick per second.',
    currentPrice: 8910.20,
    change24h: 0.54,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: '1HZ25V',
    displayName: 'Volatility 25 (1s) Index',
    category: 'Volatility Indices',
    description: 'High-frequency 25% volatility index with 1 tick per second.',
    currentPrice: 19840.10,
    change24h: 1.42,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: '1HZ50V',
    displayName: 'Volatility 50 (1s) Index',
    category: 'Volatility Indices',
    description: 'High-frequency 50% volatility index with 1 tick per second.',
    currentPrice: 38210.40,
    change24h: -0.88,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: '1HZ75V',
    displayName: 'Volatility 75 (1s) Index',
    category: 'Volatility Indices',
    description: 'High-frequency 75% volatility index with 1 tick per second.',
    currentPrice: 124580.12,
    change24h: -0.92,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: '1HZ100V',
    displayName: 'Volatility 100 (1s) Index',
    category: 'Volatility Indices',
    description: 'High-frequency 100% volatility index with rapid 1s tick pace.',
    currentPrice: 78400.30,
    change24h: 2.75,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: '1HZ150V',
    displayName: 'Volatility 150 (1s) Index',
    category: 'Volatility Indices',
    description: 'Ultra-high 150% volatility index for high speed digit scalping.',
    currentPrice: 154200.00,
    change24h: 4.10,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: '1HZ250V',
    displayName: 'Volatility 250 (1s) Index',
    category: 'Volatility Indices',
    description: 'Extreme 250% volatility index with fast tick momentum.',
    currentPrice: 289500.00,
    change24h: -3.20,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: 'CRASH1000',
    displayName: 'Crash 1000 Index',
    category: 'Crash & Boom',
    description: 'Average of 1 drop in the series every 1000 ticks. High spike potential.',
    currentPrice: 6210.30,
    change24h: -2.15,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 2000,
  },
  {
    symbol: 'CRASH500',
    displayName: 'Crash 500 Index',
    category: 'Crash & Boom',
    description: 'Average of 1 drop in series every 500 ticks. High frequency drops.',
    currentPrice: 4320.10,
    change24h: -1.85,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 2000,
  },
  {
    symbol: 'CRASH300',
    displayName: 'Crash 300 Index',
    category: 'Crash & Boom',
    description: 'Average of 1 sharp drop every 300 ticks. Maximum crash frequency.',
    currentPrice: 2850.20,
    change24h: -4.10,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 2000,
  },
  {
    symbol: 'BOOM1000',
    displayName: 'Boom 1000 Index',
    category: 'Crash & Boom',
    description: 'Average of 1 sudden spike upward every 1000 ticks.',
    currentPrice: 11450.60,
    change24h: 4.12,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 2000,
  },
  {
    symbol: 'BOOM500',
    displayName: 'Boom 500 Index',
    category: 'Crash & Boom',
    description: 'Average of 1 upward spike every 500 ticks.',
    currentPrice: 9810.75,
    change24h: 2.90,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 2000,
  },
  {
    symbol: 'BOOM300',
    displayName: 'Boom 300 Index',
    category: 'Crash & Boom',
    description: 'Average of 1 upward spike every 300 ticks.',
    currentPrice: 5410.30,
    change24h: 5.80,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 2000,
  },
  {
    symbol: 'STEPINDEX',
    displayName: 'Step Index',
    category: 'Step & Jump',
    description: 'Equal probability of up or down step movement by 0.1 size.',
    currentPrice: 8920.40,
    change24h: 0.45,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 3000,
  },
  {
    symbol: 'JUMP10',
    displayName: 'Jump 10 Index',
    category: 'Step & Jump',
    description: 'Equal probability of jumps occurring every 20 minutes on average.',
    currentPrice: 3410.50,
    change24h: 1.15,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 3000,
  },
  {
    symbol: 'JUMP25',
    displayName: 'Jump 25 Index',
    category: 'Step & Jump',
    description: 'Jump index with 25% volatility and sudden jump spikes.',
    currentPrice: 6200.80,
    change24h: 2.30,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 3000,
  },
  {
    symbol: 'JUMP50',
    displayName: 'Jump 50 Index',
    category: 'Step & Jump',
    description: 'Jump index with 50% volatility.',
    currentPrice: 12400.10,
    change24h: -1.40,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 3000,
  },
  {
    symbol: 'JUMP75',
    displayName: 'Jump 75 Index',
    category: 'Step & Jump',
    description: 'Jump index with 75% volatility.',
    currentPrice: 28900.50,
    change24h: 3.10,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 3000,
  },
  {
    symbol: 'JUMP100',
    displayName: 'Jump 100 Index',
    category: 'Step & Jump',
    description: 'Jump index with 100% volatility.',
    currentPrice: 48500.00,
    change24h: -2.80,
    isHighVolatility: true,
    minStake: 0.35,
    maxStake: 3000,
  },
  {
    symbol: 'RDBEAR',
    displayName: 'Bear Market Index',
    category: 'Volatility Indices',
    description: 'Simulates a persistent bearish market environment with negative drift.',
    currentPrice: 3210.40,
    change24h: -3.85,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  },
  {
    symbol: 'RDBULL',
    displayName: 'Bull Market Index',
    category: 'Volatility Indices',
    description: 'Simulates a persistent bullish market environment with positive drift.',
    currentPrice: 14890.20,
    change24h: 4.60,
    isHighVolatility: false,
    minStake: 0.35,
    maxStake: 5000,
  }
];

export const INITIAL_PRESET_BOTS: DBotStrategy[] = [
  {
    id: 'bot_pattern_xxy_differ',
    name: 'XXY Pattern Digit Differ Bot',
    description: 'Triggers DIGITDIFF contract dynamically targeting NOT Y (the unique current digit) whenever last 3 ticks form [X, X, Y] with Y ≠ X (e.g. 3,3,5 → DIGITDIFF 5 or 4,4,7 → DIGITDIFF 7). Dynamically updates prediction on every tick without storing past patterns.',
    symbol: 'R_100',
    category: 'DIGITS',
    contractType: 'DIGITDIFF',
    initialStake: 10,
    durationTicks: 1,
    martingaleFactor: 11.5,
    takeProfit: 50,
    stopLoss: 100,
    maxLossStreak: 2,
    rules: {
      indicatorTrigger: 'LAST_DIGIT_PATTERN',
      paramValue: 0,
    },
    totalRuns: 280,
    wins: 258,
    losses: 22,
    totalProfit: 215.40,
  },
  {
    id: 'bot_vol75_ema',
    name: 'Vol 75 Trend Master',
    description: 'Executes Rise or Fall contracts on Volatility 75 based on 10 EMA vs 50 EMA crossovers.',
    symbol: 'R_75',
    category: 'RISE_FALL',
    contractType: 'CALL',
    initialStake: 5,
    durationTicks: 5,
    martingaleFactor: 2.1,
    takeProfit: 50,
    stopLoss: 100,
    maxLossStreak: 4,
    rules: {
      indicatorTrigger: 'EMA_CROSS',
      paramValue: 10,
    },
    totalRuns: 142,
    wins: 98,
    losses: 44,
    totalProfit: 184.50,
  },
  {
    id: 'bot_crash1000_spike',
    name: 'Crash 1000 Spike Hunter',
    description: 'Monitors Crash 1000 for sudden drops, then opens PUT contract on spike reset rebound.',
    symbol: 'CRASH1000',
    category: 'RISE_FALL',
    contractType: 'PUT',
    initialStake: 10,
    durationTicks: 3,
    martingaleFactor: 2.0,
    takeProfit: 100,
    stopLoss: 150,
    maxLossStreak: 3,
    rules: {
      indicatorTrigger: 'SPIKE_DETECT',
      paramValue: 15,
    },
    totalRuns: 89,
    wins: 67,
    losses: 22,
    totalProfit: 245.00,
  },
  {
    id: 'bot_digit_differs_99',
    name: 'Digit Differs 90%+ Winrate',
    description: 'Places DIGIT DIFFERS contracts avoiding the last repeating digit on Volatility 100.',
    symbol: 'R_100',
    category: 'DIGITS',
    contractType: 'DIGITDIFF',
    initialStake: 10,
    durationTicks: 1,
    martingaleFactor: 11.5,
    takeProfit: 40,
    stopLoss: 120,
    maxLossStreak: 2,
    rules: {
      indicatorTrigger: 'LAST_DIGIT_PATTERN',
      paramValue: 1,
    },
    totalRuns: 310,
    wins: 282,
    losses: 28,
    totalProfit: 128.40,
  },
  {
    id: 'bot_accu_scalper',
    name: 'Accumulator Auto-Scalper',
    description: 'Scalps 1% to 5% growth on Volatility 75 (1s) and auto-sells after 5 safe ticks.',
    symbol: '1HZ75V',
    category: 'ACCUMULATOR',
    contractType: 'ACCU',
    initialStake: 5,
    durationTicks: 5,
    martingaleFactor: 1.5,
    takeProfit: 30,
    stopLoss: 50,
    maxLossStreak: 3,
    rules: {
      indicatorTrigger: 'ACCU_SCALP',
      paramValue: 5,
    },
    totalRuns: 120,
    wins: 91,
    losses: 29,
    totalProfit: 162.80,
  }
];

export const INITIAL_MASTER_TRADERS: MasterTrader[] = [
  {
    id: 'trader_alpha_synth',
    name: 'AlphaSynthetics',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    badge: 'PRO',
    specialtyMarket: 'Volatility 75 & 100',
    winRate: 74.8,
    totalRoi30d: 312.4,
    copiersCount: 1420,
    totalProfitUsd: 48290.00,
    maxDrawdown: 8.2,
    riskScore: 3,
  },
  {
    id: 'trader_spike_vip',
    name: 'SpikeHunter_VIP',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    badge: 'VIP',
    specialtyMarket: 'Crash 1000 & Boom 1000',
    winRate: 81.2,
    totalRoi30d: 485.1,
    copiersCount: 2190,
    totalProfitUsd: 91200.00,
    maxDrawdown: 12.5,
    riskScore: 6,
  },
  {
    id: 'trader_digit_master',
    name: 'DigitMaster_99',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    badge: 'QUANT',
    specialtyMarket: 'Digit Matches & Differs',
    winRate: 91.5,
    totalRoi30d: 198.6,
    copiersCount: 880,
    totalProfitUsd: 29400.00,
    maxDrawdown: 5.1,
    riskScore: 2,
  },
  {
    id: 'trader_step_pro',
    name: 'StepIndex_Architect',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    badge: 'TOP_GAINER',
    specialtyMarket: 'Step Index & Jump 10',
    winRate: 69.4,
    totalRoi30d: 254.2,
    copiersCount: 1105,
    totalProfitUsd: 38750.00,
    maxDrawdown: 9.8,
    riskScore: 4,
  }
];

export const INITIAL_MARKET_SIGNALS: MarketSignal[] = [
  {
    id: 'sig_1',
    symbol: 'CRASH1000',
    symbolName: 'Crash 1000 Index',
    type: 'CRASH_SPIKE_ALERT',
    time: '2 mins ago',
    confidence: 88,
    entryPrice: 6205.10,
    description: 'Large 42-point crash drop occurred. Price resetting to EMA 10 baseline.',
    recommendedTrade: 'PUT (Rise/Fall 3 Ticks)',
  },
  {
    id: 'sig_2',
    symbol: 'R_75',
    symbolName: 'Volatility 75 Index',
    type: 'BULLISH_BREAKOUT',
    time: '5 mins ago',
    confidence: 92,
    entryPrice: 845100.00,
    description: 'EMA 10 crossed above EMA 50 with RSI 68 strong upward momentum.',
    recommendedTrade: 'RISE / CALL (5 Ticks or 1 Min)',
  },
  {
    id: 'sig_3',
    symbol: 'BOOM1000',
    symbolName: 'Boom 1000 Index',
    type: 'BOOM_SPIKE_ALERT',
    time: '8 mins ago',
    confidence: 85,
    entryPrice: 11440.20,
    description: '30 consecutive small red ticks logged. High probability of upward spike in next 5-10 ticks.',
    recommendedTrade: 'RISE / CALL (10 Ticks)',
  },
  {
    id: 'sig_4',
    symbol: 'R_100',
    symbolName: 'Volatility 100 Index',
    type: 'DIGIT_REPEAT',
    time: '12 mins ago',
    confidence: 94,
    entryPrice: 42105.30,
    description: 'Digit 7 appeared 3 times in last 10 ticks. Ideal entry for Digit Differs (7).',
    recommendedTrade: 'DIGIT DIFFERS (Digit 7)',
  }
];
