import React, { useEffect, useMemo, useState } from 'react';
import { DBotStrategy, MarketInfo } from '../../types/deriv';
import { INITIAL_PRESET_BOTS } from '../../services/derivMarketsData';
import { ADDITIONAL_BOT_STRATEGIES } from '../../services/additionalBotStrategies';
import { generateDerivBotXml } from '../../utils/derivXmlGenerator';
import { Bot, Upload, Download, Play, Plus, Trash2, Search, CheckCircle2 } from 'lucide-react';

interface BotStoreProps { markets: MarketInfo[]; onImportBotToStudio: (bot: DBotStrategy) => void; }
const PRESETS=[...INITIAL_PRESET_BOTS,...ADDITIONAL_BOT_STRATEGIES];

export const BotStore: React.FC<BotStoreProps> = ({ markets, onImportBotToStudio }) => {
  const [bots,setBots]=useState<DBotStrategy[]>(PRESETS),[search,setSearch]=useState(''),[category,setCategory]=useState('ALL'),[message,setMessage]=useState('');
  const [showCreate,setShowCreate]=useState(false),[name,setName]=useState(''),[desc,setDesc]=useState(''),[symbol,setSymbol]=useState('R_100'),[stake,setStake]=useState(10),[martingale,setMartingale]=useState(11.5);
  useEffect(()=>{try{const saved=localStorage.getItem('deriv_custom_bots');if(saved)setBots([...PRESETS,...JSON.parse(saved)]);}catch{}},[]);
  const custom=bots.filter(b=>!PRESETS.some(p=>p.id===b.id));
  const save=()=>localStorage.setItem('deriv_custom_bots',JSON.stringify(custom));
  const filtered=useMemo(()=>bots.filter(b=>(category==='ALL'||b.category===category)&&(b.name.toLowerCase().includes(search.toLowerCase())||b.description.toLowerCase().includes(search.toLowerCase())||b.symbol.toLowerCase().includes(search.toLowerCase()))),[bots,search,category]);
  const exportBot=(bot:DBotStrategy,format:'json'|'xml')=>{const content=format==='json'?JSON.stringify(bot,null,2):generateDerivBotXml(bot);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:format==='xml'?'text/xml':'application/json'}));a.download=`${bot.name.toLowerCase().replace(/[^a-z0-9]+/g,'_')}.${format}`;a.click();};
  const create=()=>{if(!name.trim())return;const bot:DBotStrategy={id:`bot_custom_${Date.now()}`,name,description:desc||'Custom DBot strategy',symbol:symbol as any,category:'DIGITS',contractType:'DIGITDIFF',initialStake:stake,durationTicks:1,martingaleFactor:martingale,takeProfit:50,stopLoss:100,maxLossStreak:2,rules:{indicatorTrigger:'LAST_DIGIT_PATTERN',paramValue:2},wins:0,losses:0,totalRuns:0,totalProfit:0};const next=[bot,...bots];setBots(next);setShowCreate(false);setName('');setDesc('');localStorage.setItem('deriv_custom_bots',JSON.stringify(next.filter(b=>!PRESETS.some(p=>p.id===b.id))));setMessage(`Saved ${bot.name}`);setTimeout(()=>setMessage(''),3000);};
  const remove=(id:string)=>{const next=bots.filter(b=>b.id!==id);setBots(next);localStorage.setItem('deriv_custom_bots',JSON.stringify(next.filter(b=>!PRESETS.some(p=>p.id===b.id))));};
  const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=ev=>{try{const raw=String(ev.target?.result||'');let b:DBotStrategy;if(f.name.toLowerCase().endsWith('.json')){const x=JSON.parse(raw);b={...x,id:`bot_upload_${Date.now()}`,name:x.name||f.name,category:x.category||'DIGITS',contractType:x.contractType||'DIGITDIFF',symbol:x.symbol||'R_100',initialStake:x.initialStake||10,durationTicks:x.durationTicks||1,martingaleFactor:x.martingaleFactor||11.5,takeProfit:x.takeProfit||50,stopLoss:x.stopLoss||100,maxLossStreak:x.maxLossStreak||2,rules:x.rules||{indicatorTrigger:'LAST_DIGIT_PATTERN',paramValue:2}};}else{const n=raw.match(/<field[^>]*name=["']TEXT["'][^>]*>([^<]+)/i)?.[1]||f.name.replace(/\.xml$/i,'');b={id:`bot_upload_xml_${Date.now()}`,name:n,description:`Imported XML: ${f.name}`,symbol:'R_100',category:'DIGITS',contractType:'DIGITDIFF',initialStake:10,durationTicks:1,martingaleFactor:11.5,takeProfit:50,stopLoss:100,maxLossStreak:2,rules:{indicatorTrigger:'LAST_DIGIT_PATTERN',paramValue:2}};}const next=[b,...bots];setBots(next);save();setMessage(`Imported ${b.name}`);setTimeout(()=>setMessage(''),3000);}catch{setMessage('Could not parse the bot file.');}};r.readAsText(f);e.target.value='';};
  return <div className="space-y-5 pb-10">
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6"><div className="flex flex-col lg:flex-row justify-between gap-4"><div><div className="text-red-400 text-xs font-black flex gap-2"><Bot className="w-4 h-4"/> DERIV DBOT STRATEGY VAULT</div><h1 className="text-2xl font-black text-white mt-2">Bot Store & Strategy Repository</h1><p className="text-slate-400 text-xs mt-1">Updated catalog includes S-Differ Quad Pattern Bot (XYXX & XXYX), XXY and other strategies.</p></div><div className="flex gap-2"><label className="bg-slate-800 text-white rounded-xl px-4 py-2 text-xs font-bold cursor-pointer"><Upload className="w-4 h-4 inline mr-2"/>Upload XML/JSON<input hidden type="file" accept=".xml,.json" onChange={upload}/></label><button onClick={()=>setShowCreate(true)} className="bg-red-600 text-white rounded-xl px-4 py-2 text-xs font-bold"><Plus className="w-4 h-4 inline mr-1"/>Build Bot</button></div></div>{message&&<div className="mt-4 p-2 rounded-xl bg-emerald-950 border border-emerald-800 text-emerald-300 text-xs flex gap-2"><CheckCircle2 className="w-4 h-4"/>{message}</div>}</div>
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 flex flex-col sm:flex-row gap-3"><div className="flex gap-2 overflow-x-auto">{['ALL','DIGITS','RISE_FALL','ACCUMULATOR'].map(c=><button key={c} onClick={()=>setCategory(c)} className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap ${category===c?'bg-red-600 text-white':'bg-slate-950 text-slate-400 border border-slate-800'}`}>{c.replace('_',' ')}</button>)}</div><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search strategy, symbol or type..." className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-9 p-2 text-xs text-white"/></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map(bot=>{const preset=PRESETS.some(p=>p.id===bot.id);const wr=bot.totalRuns?((bot.wins||0)/bot.totalRuns*100).toFixed(1):'—';return <div key={bot.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex flex-col gap-4"><div className="flex justify-between"><span className="text-amber-400 font-mono text-xs">{bot.symbol}</span><span className="text-[10px] text-slate-400">{preset?'PRESET':'CUSTOM'}</span></div><div><h3 className="text-white font-extrabold text-sm">{bot.name}</h3><p className="text-slate-400 text-xs mt-1 leading-relaxed">{bot.description}</p></div><div className="grid grid-cols-3 bg-slate-950 rounded-xl p-2 text-center"><div><small className="text-slate-500">Type</small><div className="text-white text-[10px] font-bold">{bot.contractType}</div></div><div><small className="text-slate-500">Stake</small><div className="text-white text-[10px]">${bot.initialStake}</div></div><div><small className="text-slate-500">Win</small><div className="text-emerald-400 text-[10px]">{wr}%</div></div></div><button onClick={()=>onImportBotToStudio(bot)} className="w-full bg-red-600 hover:bg-red-500 text-white rounded-xl p-2.5 text-xs font-bold"><Play className="w-3 h-3 inline mr-1 fill-current"/>Import & Trade in Studio</button><div className="flex gap-2"><button onClick={()=>exportBot(bot,'json')} className="flex-1 bg-slate-950 border border-slate-800 text-slate-300 rounded-lg p-1.5 text-[10px]"><Download className="w-3 h-3 inline"/> JSON</button><button onClick={()=>exportBot(bot,'xml')} className="flex-1 bg-slate-950 border border-slate-800 text-slate-300 rounded-lg p-1.5 text-[10px]"><Download className="w-3 h-3 inline"/> XML</button>{!preset&&<button onClick={()=>remove(bot.id)} className="p-1.5 bg-slate-950 border border-slate-800 text-rose-400 rounded-lg"><Trash2 className="w-3 h-3"/></button>}</div></div>})}</div>
    {showCreate&&<div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 w-full max-w-lg space-y-3"><h3 className="text-white font-bold">Build & Store Custom Bot</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Bot name" className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white"/><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Strategy description" className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white"/><select value={symbol} onChange={e=>setSymbol(e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white">{markets.map(m=><option key={m.symbol} value={m.symbol}>{m.displayName}</option>)}</select><div className="grid grid-cols-2 gap-2"><input type="number" value={stake} onChange={e=>setStake(Number(e.target.value)||10)} placeholder="Stake" className="bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white"/><input type="number" step="0.1" value={martingale} onChange={e=>setMartingale(Number(e.target.value)||2)} placeholder="Martingale" className="bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white"/></div><div className="flex justify-end gap-2"><button onClick={()=>setShowCreate(false)} className="px-4 py-2 bg-slate-800 text-slate-300 rounded-xl text-xs">Cancel</button><button onClick={create} className="px-4 py-2 bg-red-600 text-white rounded-xl text-xs font-bold">Save Strategy</button></div></div></div>}
  </div>;
};
