import React, { useEffect, useMemo, useRef, useState } from 'react';
import { DBotStrategy, MarketInfo, MarketSymbol } from '../../types/deriv';
import { INITIAL_PRESET_BOTS } from '../../services/derivMarketsData';
import { ADDITIONAL_BOT_STRATEGIES } from '../../services/additionalBotStrategies';
import { derivWS, extractDerivLastDigit } from '../../services/derivWebSocket';
import { generateDerivBotXml } from '../../utils/derivXmlGenerator';
import { Bot, Play, Square, Settings2, Download, Zap, Activity, ShieldCheck } from 'lucide-react';

interface DBotStudioProps { markets: MarketInfo[]; balanceUsd: number; onUpdateBalance: (newBalance: number) => void; activeBotOverride?: DBotStrategy | null; }
const CATALOG: DBotStrategy[] = [...INITIAL_PRESET_BOTS, ...ADDITIONAL_BOT_STRATEGIES];

export const DBotStudio: React.FC<DBotStudioProps> = ({ markets, balanceUsd, onUpdateBalance, activeBotOverride }) => {
  const [strategies,setStrategies]=useState(CATALOG), [selectedBotId,setSelectedBotId]=useState(CATALOG[0]?.id||''), [isRunning,setIsRunning]=useState(false), [logs,setLogs]=useState<string[]>([]), [recentDigits,setRecentDigits]=useState<number[]>([]), [latestQuote,setLatestQuote]=useState(0), [sessionProfit,setSessionProfit]=useState(0), [currentStake,setCurrentStake]=useState(10), [patternStatus,setPatternStatus]=useState('IDLE');
  const [botName,setBotName]=useState(''), [botSymbol,setBotSymbol]=useState<MarketSymbol>('R_100'), [contractType,setContractType]=useState('DIGITDIFF'), [initialStake,setInitialStake]=useState(10), [martingaleFactor,setMartingaleFactor]=useState(11.5), [takeProfit,setTakeProfit]=useState(50), [stopLoss,setStopLoss]=useState(100), [durationTicks,setDurationTicks]=useState(1), [targetPrediction,setTargetPrediction]=useState(2);
  const digitsRef=useRef<number[]>([]), runningRef=useRef(false), inTradeRef=useRef(false), activeContractRef=useRef<string|null>(null), stakeRef=useRef(10), profitRef=useRef(0), targetRef=useRef(2), lastTradeRef=useRef(0), lastProcessedTickRef=useRef<string|null>(null);
  const activeBot=useMemo(()=>strategies.find(b=>b.id===selectedBotId)||strategies[0],[strategies,selectedBotId]);
  const isSDiffer=activeBot?.id==='bot_sdiffer_quad_pattern'||activeBot?.rules.indicatorTrigger==='S_DIFFER_QUAD_PATTERN';
  const isXxy=activeBot?.id==='bot_pattern_xxy_differ'||activeBot?.rules.indicatorTrigger==='LAST_DIGIT_PATTERN'||activeBot?.name.toLowerCase().includes('xxy');
  const isAlternating=activeBot?.id==='bot_alternating_digit_diff'||activeBot?.rules.indicatorTrigger==='ALTERNATING_DIGIT_DIFF';
  const log=(m:string)=>setLogs(p=>[`[${new Date().toLocaleTimeString()}] ${m}`,...p].slice(0,80));

  useEffect(()=>{ if(!activeBot)return; setBotName(activeBot.name);setBotSymbol(activeBot.symbol);setContractType(activeBot.contractType);setInitialStake(activeBot.initialStake);setCurrentStake(activeBot.initialStake);setMartingaleFactor(activeBot.martingaleFactor);setTakeProfit(activeBot.takeProfit);setStopLoss(activeBot.stopLoss);setDurationTicks(activeBot.durationTicks||1);setTargetPrediction(activeBot.rules.paramValue??2);targetRef.current=activeBot.rules.paramValue??2;stakeRef.current=activeBot.initialStake; },[activeBot]);
  useEffect(()=>{ if(!activeBotOverride)return; setStrategies(p=>p.some(b=>b.id===activeBotOverride.id)?p:[activeBotOverride,...p]);setSelectedBotId(activeBotOverride.id);setIsRunning(false);log(`Strategy "${activeBotOverride.name}" loaded into Bot Studio.`); },[activeBotOverride]);

  // Single tick collector: keep one authoritative sliding window and de-duplicate
  // ticks by Deriv tick id/epoch so the strategy evaluator never appends a tick twice.
  useEffect(()=>{
    digitsRef.current=[]; setRecentDigits([]); lastProcessedTickRef.current=null;
    const h=(t:any)=>{
      const q=Number(t.quote); if(!Number.isFinite(q))return;
      const tickKey=t.id!=null?String(t.id):t.epoch!=null?String(t.epoch):`${t.symbol||botSymbol}:${q}`;
      if(tickKey&&tickKey===lastProcessedTickRef.current)return;
      lastProcessedTickRef.current=tickKey;
      const d=extractDerivLastDigit(q); setLatestQuote(q);
      const n=[...digitsRef.current.slice(-19),d]; digitsRef.current=n; setRecentDigits(n);
    };
    derivWS.subscribeTicks(botSymbol,h); return()=>derivWS.unsubscribeTicks(botSymbol,h);
  },[botSymbol]);

  const buy=(target:number,reason:string)=>{if(inTradeRef.current)return;const now=Date.now();if(isAlternating&&now-lastTradeRef.current<5000){setPatternStatus('SCANNING');return;}targetRef.current=target;setTargetPrediction(target);lastTradeRef.current=now;inTradeRef.current=true;setPatternStatus('SETTLING');const symbolName=markets.find(m=>m.symbol===botSymbol)?.displayName||botSymbol;const c=derivWS.purchaseContract({symbol:botSymbol,contractType:'DIGITDIFF',stake:stakeRef.current,durationTicks:1,targetDigit:target,barrier:target,symbolName});activeContractRef.current=c.id;log(`🎯 ${reason} → DIGITDIFF ${target} | $${stakeRef.current.toFixed(2)} | 1 tick`);};

  useEffect(()=>{if(!isRunning)return;runningRef.current=true;const h=(t:any)=>{if(!runningRef.current||inTradeRef.current)return;const tickKey=t.id!=null?String(t.id):t.epoch!=null?String(t.epoch):'';if(tickKey&&tickKey===lastProcessedTickRef.current)return;const n=digitsRef.current;if(!n.length)return;
    if(isSDiffer&&n.length>=4){const[d1,d2,d3,d4]=n.slice(-4),xyxx=d1===d3&&d3===d4&&d2!==d1,xxyx=d1===d2&&d2===d4&&d3!==d1;if(xyxx||xxyx)buy(d4,`S-DIFFER ${xyxx?'XYXX':'XXYX'} [${d1},${d2},${d3},${d4}] (X=${d4}, Y=${xyxx?d2:d3})`);else setPatternStatus('SCANNING');return;}
    if(isXxy&&n.length>=3){const[d1,d2,d3]=n.slice(-3);if(d1===d2&&d3!==d1)buy(d3,`XXY [${d1},${d2},${d3}]`);else setPatternStatus('SCANNING');return;}
    if(isAlternating&&n.length>=2){const[d1,d2]=n.slice(-2);if(d1!==d2)buy(targetRef.current||5,`ALTERNATING [${d1}→${d2}]`);else setPatternStatus('SCANNING');return;}
    if(n.length>=1)buy(targetRef.current,`GENERAL ${botSymbol} signal`);
  };derivWS.subscribeTicks(botSymbol,h);return()=>{runningRef.current=false;derivWS.unsubscribeTicks(botSymbol,h);};},[isRunning,botSymbol,isSDiffer,isXxy,isAlternating]);

  useEffect(()=>{const h=(c:any)=>{if(!activeContractRef.current||c.id!==activeContractRef.current||!['WON','LOST','SOLD'].includes(c.status))return;const p=Number(c.currentProfit)||0;profitRef.current+=p;setSessionProfit(profitRef.current);
    // Live authenticated accounts receive the authoritative balance from the WebSocket
    // balance subscription/refresh. Do not optimistically add P/L and double-count it.
    if(!derivWS.getIsLiveWs())onUpdateBalance(balanceUsd+p);
    if(p>0){stakeRef.current=initialStake;setCurrentStake(initialStake);log(`🏆 SETTLED WON +$${p.toFixed(2)} → stake reset $${initialStake.toFixed(2)} | Deriv balance refresh requested`);}else{const ns=Number((stakeRef.current*martingaleFactor).toFixed(2));stakeRef.current=ns;setCurrentStake(ns);log(`❌ SETTLED LOST -$${Math.abs(p).toFixed(2)} → next stake $${ns.toFixed(2)} | Deriv balance refresh requested`);}inTradeRef.current=false;activeContractRef.current=null;setPatternStatus('SCANNING');if(profitRef.current>=takeProfit){log(`🎯 TAKE PROFIT +$${profitRef.current.toFixed(2)} → STOPPED`);setIsRunning(false);runningRef.current=false;}if(profitRef.current<=-stopLoss){log(`🛑 STOP LOSS -$${Math.abs(profitRef.current).toFixed(2)} → STOPPED`);setIsRunning(false);runningRef.current=false;}};derivWS.subscribeContracts(h);return()=>derivWS.unsubscribeContracts(h);},[balanceUsd,initialStake,martingaleFactor,takeProfit,stopLoss,onUpdateBalance]);

  const toggle=()=>{if(isRunning){runningRef.current=false;inTradeRef.current=false;setIsRunning(false);setPatternStatus('IDLE');log(`🛑 STOPPED by user | Session P/L $${profitRef.current.toFixed(2)}`);return;}profitRef.current=0;setSessionProfit(0);stakeRef.current=initialStake;setCurrentStake(initialStake);inTradeRef.current=false;setIsRunning(true);runningRef.current=true;setPatternStatus('SCANNING');log(`🟢 STARTED ${activeBot.name} on ${botSymbol} using continuous real Deriv ticks`);};
  const save=()=>{setStrategies(p=>p.map(b=>b.id===activeBot.id?{...b,name:botName,symbol:botSymbol,contractType,initialStake,martingaleFactor,takeProfit,stopLoss,durationTicks,rules:{...b.rules,paramValue:targetPrediction}}:b));log(`✅ Saved "${botName}".`);};
  const exportXml=()=>{const b={...activeBot,name:botName,symbol:botSymbol,contractType,initialStake,martingaleFactor,takeProfit,stopLoss,durationTicks,rules:{...activeBot.rules,paramValue:targetPrediction}};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([generateDerivBotXml(b)],{type:'text/xml'}));a.download=`${botName.toLowerCase().replace(/[^a-z0-9]+/g,'_')}_deriv_bot.xml`;a.click();log(`📥 Exported ${a.download}.`);};
  if(!activeBot)return <div className="p-6 text-white">No strategies.</div>;

  return <div className="space-y-5 pb-10">
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="text-red-400 text-xs font-black flex gap-2"><Bot className="w-4 h-4"/> DERIV DBOT STUDIO • LIVE TICK ENGINE</div><h1 className="text-2xl font-black text-white mt-2">Updated Bot Strategy Studio</h1><p className="text-slate-400 text-xs">Real Deriv ticks → pattern detection → DIGITDIFF → next-tick settlement.</p></div><button onClick={toggle} className={`px-6 py-3 rounded-2xl font-black text-xs flex gap-2 items-center ${isRunning?'bg-rose-600':'bg-emerald-600'} text-white`}>{isRunning?<Square className="w-4 h-4"/>:<Play className="w-4 h-4"/>}{isRunning?'STOP AUTO-TRADER':'START AUTO-TRADER'}</button></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><div className="space-y-5">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4"><h3 className="text-white font-bold text-sm mb-3 flex gap-2"><Settings2 className="w-4 h-4 text-red-400"/> Select Strategy</h3><div className="space-y-2 max-h-80 overflow-y-auto">{strategies.map(b=><button key={b.id} disabled={isRunning} onClick={()=>setSelectedBotId(b.id)} className={`w-full text-left p-3 rounded-xl border ${selectedBotId===b.id?'border-red-600 bg-red-950/30':'border-slate-800 bg-slate-950/60'}`}><div className="flex justify-between gap-2"><b className="text-white text-xs">{b.name}</b><span className="text-amber-400 text-[10px]">{b.symbol}</span></div><p className="text-slate-400 text-[10px] mt-1">{b.description}</p></button>)}</div></div>
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3"><h3 className="text-white font-bold text-sm">Strategy Parameters</h3><input value={botName} disabled={isRunning} onChange={e=>setBotName(e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white"/><select value={botSymbol} disabled={isRunning} onChange={e=>setBotSymbol(e.target.value as MarketSymbol)} className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white">{markets.map(m=><option key={m.symbol} value={m.symbol}>{m.displayName}</option>)}</select><div className="grid grid-cols-2 gap-2">{[['Stake',initialStake,setInitialStake],['Martingale',martingaleFactor,setMartingaleFactor],['Take Profit',takeProfit,setTakeProfit],['Stop Loss',stopLoss,setStopLoss],['Duration',durationTicks,setDurationTicks],['Target',targetPrediction,setTargetPrediction]].map(([n,v,s]:any)=><label key={n} className="text-[10px] text-slate-400">{n}<input type="number" value={v as number} disabled={isRunning} onChange={e=>{const x=Number(e.target.value)||1;s(x);if(n==='Stake')stakeRef.current=x;if(n==='Target')targetRef.current=x;}} className="w-full mt-1 bg-slate-950 border border-slate-800 rounded-xl p-2 text-xs text-white"/></label>)}</div><div className="flex gap-2"><button onClick={save} disabled={isRunning} className="flex-1 bg-slate-800 text-white rounded-xl p-2 text-xs font-bold">Save Adjustments</button><button onClick={exportXml} className="p-2 bg-emerald-950 text-emerald-300 rounded-xl"><Download className="w-4 h-4"/></button></div></div>
    </div><div className="lg:col-span-2 space-y-5">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4"><div className="flex justify-between"><h3 className="text-white font-extrabold text-sm flex gap-2"><Zap className="w-5 h-5 text-amber-400"/>{isSDiffer?'S-Differ Pattern Engine (XYXX & XXYX)':isXxy?'XXY Pattern Digit Differ Engine':isAlternating?'Alternating Digit Difference Engine':`${activeBot.name} Engine`}</h3><span className="text-xs text-emerald-400">{patternStatus}</span></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{[['Quote',latestQuote?latestQuote.toFixed(2):'Loading...'],['Stake',`$${currentStake.toFixed(2)}`],['Session P/L',`$${sessionProfit.toFixed(2)}`],['Balance',`$${balanceUsd.toFixed(2)}`]].map(([a,v])=><div key={a} className="bg-slate-950 rounded-xl p-3"><span className="text-slate-500 text-[10px]">{a}</span><div className="text-white font-mono font-bold">{v}</div></div>)}</div><div className="bg-slate-950 border border-slate-800 rounded-xl p-4"><div className="flex justify-between mb-2"><span className="text-slate-300 text-xs font-bold">Live Deriv Tick Stream • {botSymbol}</span><span className="text-amber-400 text-[10px]">{isSDiffer?'4-tick window':isXxy?'3-tick window':'latest ticks'}</span></div><div className="flex gap-2 overflow-x-auto">{recentDigits.map((d,i)=><span key={`${i}-${d}`} className={`min-w-9 h-9 rounded-lg flex items-center justify-center font-mono font-black ${i>=recentDigits.length-(isSDiffer?4:isXxy?3:2)?'bg-emerald-900 text-emerald-300 border border-emerald-600':'bg-slate-900 text-slate-500 border border-slate-800'}`}>{d}</span>)}</div></div>{isSDiffer&&<div className="grid md:grid-cols-2 gap-2 text-xs text-emerald-300"><div className="bg-emerald-950/40 border border-emerald-800 rounded-xl p-3"><b>XYXX:</b> 2,5,2,2 → Differ 2</div><div className="bg-emerald-950/40 border border-emerald-800 rounded-xl p-3"><b>XXYX:</b> 2,2,5,2 → Differ 2</div></div>}{isXxy&&<div className="bg-emerald-950/40 border border-emerald-800 rounded-xl p-3 text-xs text-emerald-300"><b>XXY:</b> X,X,Y with Y ≠ X. Example 3,3,5 → DIGITDIFF 5.</div>}</div>
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex justify-between mb-3"><h3 className="text-white font-bold text-sm flex gap-2"><Activity className="w-4 h-4 text-emerald-400"/> Execution Log</h3><button onClick={()=>setLogs([])} className="text-slate-500 text-xs">Clear</button></div><div className="h-72 overflow-y-auto bg-slate-950 rounded-xl p-3 font-mono text-[11px] space-y-1">{logs.length?logs.map((l,i)=><div key={i} className={l.includes('WON')?'text-emerald-400':l.includes('LOST')?'text-rose-400':l.includes('DIGITDIFF')||l.includes('DETECTED')?'text-amber-300':'text-slate-300'}>{l}</div>):<div className="text-slate-600 text-center pt-10">Start the auto-trader to see live logs.</div>}</div></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 text-[11px] text-slate-400 flex gap-2"><ShieldCheck className="w-4 h-4 text-emerald-400"/> Real authenticated Deriv WebSocket execution. Digit strategies settle after 1 tick before the next entry.</div>
    </div></div></div>;
};